name: Publish

on:
  push:
    branches:
    - main

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

      with:
        fetch-depth: 0

    - uses: actions/setup-node@v5
      with:
        node-version: 24

        registry-url: 'https://registry.npmjs.org'

    - run: npm ci

    - run: |
        git config user.email "$(git show -s --format=%ae)"
        git config user.name "$(git show -s --format=%an)"

    - run: npm run release

    - run: npm publish

    - uses: kellyselden/move-semver-tags-action@v7
      with:
        copy-annotations: true
